### ISSUE TITLE
negative-sampling issue

### ISSUE THREAD

**Issue by lonelyandrew** [yasiemir/cs224n#1]
Hi, Yasir Mir:

In `q3_word2vec.py`, 
```python
def negSamplingCostAndGradient...
    indices = [target]
    indices.extend(getNegativeSamples(target, dataset, K))
    ...
    sample = outputVectors[indices] #line142
    ...
```

I think the `indices` contains the `target` which is the $u_o$ in the formula.
So the `cost` and other value are calculated with $u_o$ redundantly.

**Comment by yasiemir** [comment]
I am assuming that `target` can be sampled in negative samples, as discussed in lectures but clearly instructed to avoid in assignment notes. If you're looking for a solution for `o` not sampled in `k`, head over to [Zafar's repo.](https://github.com/zaffnet/cs224n)

**Comment by lonelyandrew** [comment]
OK, I get it. Thanks for the explanation.
